package wire

import (
	"bytes"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

var FrameworkProviders = map[string]string{
	"bus.EventBus": "bus.NewLocalBus()",
}

func sanitizeVarName(name string) string {
	return strings.ReplaceAll(name, ".", "_")
}

const wireTmpl = `// Code generated by GoX CLI. DO NOT EDIT.
package {{.PkgName}}

import "gox/pkg/bus" // Added for MVP

func WireApp() *App {
{{- range .Providers}}
	_{{.VarName}} := {{.InitCode}}
{{- end}}
{{- range .Nodes}}
	_{{.Name}} := &{{.Name}}{}
{{- end}}

{{- range .Nodes}}
	{{- $nodeName := .Name}}
	{{- range .Dependencies}}
	_{{$nodeName}}.{{.FieldName}} = _{{.TypeName}}
	{{- end}}
{{- end}}

	return _App
}
`

type Provider struct {
	VarName  string
	InitCode string
}

type GeneratorData struct {
	PkgName   string
	Nodes     []StructNode
	Providers []Provider
}

// Generate build the wire_gen.go file.
func Generate(dirPath string, nodes []StructNode, pkgName string) error {
	// 1. Filter nodes to only those reachable from "App" to avoid unused variable errors
	nodeMap := make(map[string]StructNode)
	for _, n := range nodes {
		nodeMap[n.Name] = n
	}

	reachable := make(map[string]bool)
	usedProviders := make(map[string]bool)
	var queue []string
	if _, ok := nodeMap["App"]; ok {
		queue = append(queue, "App")
		reachable["App"] = true
	}

	for len(queue) > 0 {
		curr := queue[0]
		queue = queue[1:]

		node, exists := nodeMap[curr]
		if !exists {
			continue // Might be a built-in type or from another package
		}

		for i, dep := range node.Dependencies {
			// Sanitize var name
			node.Dependencies[i].TypeName = dep.TypeName
			
			if _, isProvider := FrameworkProviders[dep.TypeName]; isProvider {
				usedProviders[dep.TypeName] = true
			} else if !reachable[dep.TypeName] {
				reachable[dep.TypeName] = true
				queue = append(queue, dep.TypeName)
			}
		}
		// Update node in map after changing dependencies
		nodeMap[curr] = node
	}

	var filteredNodes []StructNode
	for name := range reachable {
		node := nodeMap[name]
		// Create a sanitized dependency list for the template
		var sanitizedDeps []struct{ FieldName, VarName string }
		for _, dep := range node.Dependencies {
			sanitizedDeps = append(sanitizedDeps, struct{ FieldName, VarName string }{
				FieldName: dep.FieldName,
				VarName:   sanitizeVarName(dep.TypeName),
			})
		}
		// Override dependencies with sanitized names
		// We use a trick: the template loops over Dependencies, we can just replace them.
		// Wait, StructNode.Dependencies is type Dependency.
		for i := range node.Dependencies {
			node.Dependencies[i].TypeName = sanitizeVarName(node.Dependencies[i].TypeName)
		}
		filteredNodes = append(filteredNodes, node)
	}

	var providers []Provider
	for p := range usedProviders {
		providers = append(providers, Provider{
			VarName:  sanitizeVarName(p),
			InitCode: FrameworkProviders[p],
		})
	}

	// 2. Generate Code
	data := GeneratorData{
		PkgName:   pkgName,
		Nodes:     filteredNodes,
		Providers: providers,
	}

	tmpl, err := template.New("wire").Parse(wireTmpl)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	// 3. Format the generated code
	formattedCode, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, write unformatted code for debugging
		formattedCode = buf.Bytes()
	}

	// 4. Write to gox_wire_gen.go
	outPath := filepath.Join(dirPath, "gox_wire_gen.go")
	return os.WriteFile(outPath, formattedCode, 0644)
}
