// Code generated by GoX CLI. DO NOT EDIT.
package main

import "gox/pkg/bus" // Added for MVP

func WireApp() *App {
	_bus_EventBus := bus.NewLocalBus()
	_UserController := &UserController{}
	_NotificationService := &NotificationService{}
	_UserService := &UserService{}
	_UserRepository := &UserRepository{}
	_App := &App{}
	_UserController.Service = _UserService
	_NotificationService.Bus = _bus_EventBus
	_UserService.Repo = _UserRepository
	_UserService.Bus = _bus_EventBus
	_App.UserController = _UserController
	_App.NotificationService = _NotificationService

	return _App
}
